// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://acesso.aniversariantevip.com.br";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51Z3lvcWdicmpxZ3RvcGttZHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyOTc0NzksImV4cCI6MjA4MDg3MzQ3OX0.lb42PMOHJWonmM4ATk6SJO1-Ib1D4l_IUTw2kROwRxQ";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
